import { Schema } from 'ts-api-validator';
export declare const issueTransactionSchema: Schema;
export declare const transferTransactionSchema: Schema;
export declare const reissueTransactionSchema: Schema;
export declare const burnTransactionSchema: Schema;
export declare const exchangeTransactionSchema: Schema;
export declare const leaseTransactionSchema: Schema;
export declare const cancelLeasingTransactionSchema: Schema;
export declare const createAliasTransactionSchema: Schema;
export declare const massTransferTransactionSchema: Schema;
