import { IAssetObject, IWavesBasicConfig, IWavesConfig } from '../interfaces';
export declare const WAVES = "WAVES";
export declare const WAVES_PROPS: IAssetObject;
export declare const MAINNET_BYTE: number;
export declare const TESTNET_BYTE: number;
export declare const INITIAL_NONCE = 0;
export declare const ADDRESS_VERSION = 1;
export declare const ALIAS_VERSION = 2;
export declare const ISSUE_TX = 3;
export declare const TRANSFER_TX = 4;
export declare const REISSUE_TX = 5;
export declare const BURN_TX = 6;
export declare const EXCHANGE_TX = 7;
export declare const LEASE_TX = 8;
export declare const CANCEL_LEASING_TX = 9;
export declare const CREATE_ALIAS_TX = 10;
export declare const MASS_TRANSFER_TX = 11;
export declare const MASS_TRANSFER_TX_VERSION = 1;
export declare const ISSUE_TX_NAME = "issue";
export declare const TRANSFER_TX_NAME = "transfer";
export declare const REISSUE_TX_NAME = "reissue";
export declare const BURN_TX_NAME = "burn";
export declare const EXCHANGE_TX_NAME = "exchange";
export declare const LEASE_TX_NAME = "lease";
export declare const CANCEL_LEASING_TX_NAME = "cancelLeasing";
export declare const CREATE_ALIAS_TX_NAME = "createAlias";
export declare const MASS_TRANSFER_TX_NAME = "massTransfer";
export declare const PRIVATE_KEY_LENGTH = 32;
export declare const PUBLIC_KEY_LENGTH = 32;
export declare const MINIMUM_FEE = 100000;
export declare const MINIMUM_ISSUE_FEE = 100000000;
export declare const MINIMUM_MATCHER_FEE = 300000;
export declare const TRANSFER_ATTACHMENT_BYTE_LIMIT = 140;
export declare const DEFAULT_MIN_SEED_LENGTH = 25;
export declare const DEFAULT_ORDER_EXPIRATION_DAYS = 20;
export declare const DEFAULT_BASIC_CONFIG: IWavesBasicConfig;
export declare const DEFAULT_MAINNET_CONFIG: IWavesConfig;
export declare const DEFAULT_TESTNET_CONFIG: IWavesConfig;
export declare const WAVES_V1_ISSUE_TX: {
    assetId: string;
    decimals: number;
    description: string;
    fee: number;
    height: number;
    id: string;
    name: string;
    quantity: number;
    reissuable: boolean;
    sender: string;
    senderPublicKey: string;
    signature: string;
    timestamp: number;
    type: number;
};
